// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS8uGnvh9devolxGi8jSNridCsgs0U5TA',
    appId: '1:790321025263:android:dbfda6fd0194e2d8084b1a',
    messagingSenderId: '790321025263',
    projectId: 'bbuild-pmob',
    databaseURL: 'https://bbuild-pmob-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bbuild-pmob.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2cL5ARKfrSGoZBNT4q2fHQP6ydQRCCwI',
    appId: '1:790321025263:ios:2a85d17e2ea6e274084b1a',
    messagingSenderId: '790321025263',
    projectId: 'bbuild-pmob',
    databaseURL: 'https://bbuild-pmob-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bbuild-pmob.appspot.com',
    androidClientId: '790321025263-c7bumps3fm7u7a9egnsoutlemnk9ad36.apps.googleusercontent.com',
    iosClientId: '790321025263-jfp6mhi4usghaf54guvrpmup80l35uo5.apps.googleusercontent.com',
    iosBundleId: 'com.example.bbuild',
  );
}
